### ISSUE TITLE
能不能加一个部署的说明

### ISSUE THREAD

**Issue by LiangShang** [dantin/catalyst-blog#1]
看了您的博客，感觉内容很丰富。请问有没有部署说明啊？我也想部署一个。谢谢啦！！

**Comment by dantin** [comment]
安装

首先确保Nodejs和Git都安装好。

npm install -g hexo
创建工程目录

1
2
3
hexo init <folder>
cd <folder>
hexo init
使用入门

新建文章

hexo new "My New Post"
More info: Writing

启动服务器

hexo server
